# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67ad4d496d2d66887722d8b6ec8929ba2c4ab2d2a240354aa9683837db59c9646fcd805bab0930812c5229c2964a4dd6e4ac510f1ce1e273732479edc43441dd

test:
  secret_key_base: 8029945532694f3970719d8a2b8e06db2f87e3fe249578e05d22706ef527d485095f62ea1b1298accf74cabaedfc93ad44ec73f416ea4f450796cd42fdf8afee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
